// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use environment variables with fallback to hardcoded values for development
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://bftpowyordxqpavpqglp.supabase.co";
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmdHBvd3lvcmR4cXBhdnBxZ2xwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1MTIwMTEsImV4cCI6MjA2MzA4ODAxMX0.QKzDwHDu56TJQm38Teqx5aYj1amDOUGa41fCNbqfHKE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY);